### ISSUE TITLE
landsat notebook time series issue

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo-tutorial-agu-2018#12]
@scottyhq had a fix for the landsat notebook time series issue that involved tagging some version of some package, but I can't remember what it was

**Comment by scottyhq** [comment]
Was seeing this error with dask/msgpack when plotting the time series with hvplot.
https://github.com/explosion/spaCy/issues/2996 

This seems to fix it:
conda install msgpack-python=0.5.6 nomkl -c conda-forge 

We should probably make sure this doesn't affect the other notebooks, then pin all the versions to avoid future breaks.

**Comment by rabernat** [comment]
Is this fixed?

**Comment by scottyhq** [comment]
closing b/c adding new notebooks for 2019
