### ISSUE TITLE
Do we want to maintain this repo?

### ISSUE THREAD

**Issue by guillaumeeb** [pangeo-data/pangeo-tutorial-agu-2018#13]
Hi,

I'm looking for a good tutorial on Pangeo for a workshop next week, the repo looks really promising and when testing this morning it seems to work fine. Question are:
- there are a few tiny mistakes in the notebooks/Welcome.md file, do we want to fix them?
- More generally do we want to maintain this? I think this is really important to have this kind of tutorial for Pangeo.
- Did I miss a more up to date binder repo for doing tutorial?

**Comment by rabernat** [comment]
> * there are a few tiny mistakes in the notebooks/Welcome.md file, do we want to fix them?

Yes! I have just created a branch `agu2018` so we have an "archive" of the actual AGU tutorial

> * More generally do we want to maintain this? I think this is really important to have this kind of tutorial for Pangeo.

I am happy to repurpose this as a general-purpose pangeo tutorial. In that case, do we also want to rename it to just `pangeo-tutorial`?

> * Did I miss a more up to date binder repo for doing tutorial?

I often use https://github.com/pangeo-data/pangeo_ocean_examples/, but this is a more ocean-focused theme.

**Comment by guillaumeeb** [comment]
> I am happy to repurpose this as a general-purpose pangeo tutorial. In that case, do we also want to rename it to just pangeo-tutorial?

I think this would be very nice to have a maintained (even if this is only a best effort) repo for all around pangeo tutorial, and this one is a good start! If several folks use it regularly, we could maintain it every time we find something wrong. But experience has shown that this is hard to prevent this kind of repo to become stale.

**Comment by jhamman** [comment]
I've renamed this to `pangeo-tutorial`. I'll be spending some time here tomorrow prepping for a tutorial I'll be giving next week.

**Comment by guillaumeeb** [comment]
Thanks @jhamman! 

I'll use it again for a tutorial early june. I'll benefit from your update!
