### ISSUE TITLE
Updates from C3DIS

### ISSUE THREAD

**Issue by jmunroe** [pangeo-data/pangeo-tutorial-agu-2018#16]
Based on going through these tutorials as C3DIS we found some issues that need to be updated.  For future reference:

xarray notebook: `sst_ts_rolling = sst_ts.rolling(time=24, center=True).mean()`

Landsat8 notebook:  `band1 = da.sel(band=1).drop('band').persist()`
 (other wise hvplot sees the 'band' coord and interprets it as RGB)

gmet_ensemble notebook: `ax = pcp_ann_max_ts.plot.line(x='time', add_legend=False)`
is more readable (and faster!)

**Comment by guillaumeeb** [comment]
Hi @jmunroe!

Thanks for the feedback here.

I understand you've forked the repo for your tutorial. Did you make the suggested change on your repo? Would it be possible to open one or several PRs for them?

And also, as you mention Landsat8 notebook, did you run into the issue described in #12?

**Comment by jhamman** [comment]
closed in e1100ad
