### ISSUE TITLE
404 not found on dask windows

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-tutorial-agu-2018#7]
This is what I see when I load up the binder

![image](https://user-images.githubusercontent.com/1197350/49846009-29ebac00-fd97-11e8-906c-776d0bf51479.png)

**Comment by jhamman** [comment]
I'm in the process of pinning the dask lab extension to the last version that I know worked. Fix coming soon.

**Comment by jhamman** [comment]
This isn't an issue anymore. Fixed upstream in dask-labextension.
